apiVersion: apps/v1
kind: Deployment
metadata:
  name: rachrafi
  namespace: rachrafi
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  rachrafi
  template:
    metadata:
      labels:
        app:  rachrafi
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  rachrafi
        image: rachrafi.jfrog.io/rachrafi-docker-local/demo-workshop:2.1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: CONSUMER_KEY
          value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
        - name: CONSUMER_SECRET
          value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
        - name: ACCESS_TOKEN
          value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
        - name: ACCESS_TOKEN_SECRET
          value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"
