apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: rachrafi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyYWNocmFmaS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiY21GaWFTNWhZMmh5WVdacFFHZHRZV2xzTG1OdmJUcHBZbUZ5U2taU1QwY3hPVGM0SVE9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson