apiVersion: v1
kind: Service
metadata:
  name:  rachrafi-service
  namespace: rachrafi
spec:
  type: NodePort
  selector:
    app: rachrafi
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000